### PR TITLE
Clean up code and files; label o.o.p. sensors; "Saltwater"

### PR DESCRIPTION
**Pull request by bpbond**
* Make it so app doesn't crash if gmailr not authorized
* Move metadata files into their own subfolder
* Clean up indentation
* Map out-of-plot sapflow sensors into closest grid square and label "[OUT]"
* Standardize on "Saltwater"
* Change maps code to be a [module](https://shiny.posit.co/r/articles/improve/modules/) in new `R/` folder

### CODE REVIEW

**Comment by bpbond** [comment]
@stephpenn1 Re #102 here in a809323b5b7d599b29b0843f0cf774d02a0eae5e is a first attempt at displaying out-of-plot sapflow sensors:

Screenshot 2023-06-17 at 10 06 08 AM

(I've hand-annotated the red arrows; they don't appear in the app.) Basically, out-of-plot sensors are shown **in the grid square closest to where their location**, and labeled "[OUT]".

**Comment by bpbond** [comment]
Final change for this PR: in a809323b5b7d599b29b0843f0cf774d02a0eae5e standardize plot name "Saltwater" — #105 — instead of "Salt" (was used in tree inventory) or "Seawater" (in the TEROS files). Note that changes were made both in the `Design/` documents as well as the Shiny-local copies. Some code tweaks as well.

**Comment by bpbond** [comment]
I was reading about [Shiny modules](https://shiny.posit.co/r/articles/improve/modules/), got interested, and tried moving the maps code into a new `R/maps_module.R` file that is automatically read when the app starts. This has some nice benefits in terms of separating code into manageable chunks, and will make testing easier if we want to do that (see #110 ). Finally, it provides a template for more modularization in the future.

**Comment by stephpenn1** [comment]
this is great! love the module idea. i dont have any notes or edits

**Comment by bpbond** [comment]
Thank you

**Pull request merged**
