### PR TITLE
Add a GitHub Action: knit any changed R Markdown files

### PR DESCRIPTION
**Pull request by bpbond**

### CODE REVIEW

**Comment by bpbond** [comment]
@ahopple @stephpenn1 Can one of you please turn on GitHub Actions for this repository? 

Settings -> Actions -> Allow all actions

**Comment by ahopple** [comment]
It's already set to "allow all actions" - ??

**Comment by ahopple** [comment]
uh. never replying to the email again.

**Comment by bpbond** [comment]
😆  okay thank you I will double-check on my end then

**Comment by ahopple** [comment]
I could try setting it to something else and re-setting it?

**Comment by bpbond** [comment]
Ah nope it was my mistake :)  didn't have the needed trigger condition. Carry on! Thank you

**Comment by bpbond** [comment]
Hi @stephpenn1 @ahopple -

So this PR adds a "GitHub Action" which basically is an automated check that runs every time a PR is opened. In this case, if any R Markdown files in the repository have been changed, the Action ensures that they run without error. Does this seem reasonable?

Alternatives we could implement:
* Re-run ALL R Markdown files on every PR, to ensure that data or file structure changes haven't broken anything
* Run specific R scripts (e.g. the current TEROS script) and ensure they work, again on every PR

Feedback welcome 🙏

**Review by stephpenn1 — APPROVED** [review]

**Comment by stephpenn1** [comment]
Nice this looks good. Let's keep this check as is for now. I like to idea of adding in major processing scripts later on.

**Pull request merged**
