### PR TITLE
TEROS pipeline - improve speed and memory consumption, outlier detection

### PR DESCRIPTION
**Pull request by bpbond**
See my comments in #23

### CODE REVIEW

**Comment by bpbond** [comment]
Would it be useful to discuss this @ahopple ?

**Comment by stephpenn1** [comment]
@bpbond @ahopple if this is good to go, can we merge so I can pull from it for the qa/qc document (issue #50 )

**Comment by bpbond** [comment]
Let's just merge

**Comment by bpbond** [comment]
Thank you @stephpenn1  - this was my PR obviously so please tell me if anything is unclear.

**Pull request merged**
