### PR TITLE
Dashboard pane graphs

### PR DESCRIPTION
**Pull request by bpbond**
@stephpenn1 

This PR has a bunch of things in it (if too much, I can split them apart):
* Add graphs for sapflow, TEROS, AquaTroll, and battery 
* Better handle no data and running outside of Shiny
* Add a "TESTING" mode (defined in `global.R`). If TRUE, the app uses pre-stored data and doesn't go to Dropbox at all; it also changes color to warn the user that this isn't live
* All four badges' label and color are dynamically calculated from the data - currently last hour
* Added preliminary `process_aquatroll()` function. This will need to be modified depending on Dropbox structure
* Removed dead/comment-out code and expanded comments

Related: see #83 #82 

Ready for your review and feedback.

### CODE REVIEW

**Comment by bpbond** [comment]
If no available show a nice message:

Screen Shot 2022-06-15 at 11 43 43 AM

**Comment by bpbond** [comment]
Added a "TESTING" mode, so we can try out changes without constantly having to re-sync from Dropbox. When this is enabled, the server reads pre-stored data, and the dashboard changes appearance so we'll never be confused:

Screen Shot 2022-06-16 at 5 52 21 PM

**Comment by bpbond** [comment]
🎉  In commit 707ba53 we have a dynamic dashboard badge! 

Screen Shot 2022-06-16 at 10 02 39 PM

**Comment by stephpenn1** [comment]
Awesome!! Rerunning the from dropbox is so annoying

**Comment by stephpenn1** [comment]
this is AWESOME

**Review by stephpenn1 — APPROVED** [review]

**Comment by bpbond** [comment]
OK, signing off. Implemented AquaTroll code, badge, graph; right now it's only graphing the `Temp` column because I wasn't sure which/how many we wanted to visualize.

When run in test mode, things look like this:

Screen Shot 2022-06-18 at 11 00 59 AM

When pulling data from Dropbox:

Screen Shot 2022-06-18 at 10 58 38 AM

There's no AquaTroll data in my Dropbox folder, which is anyway disconnected from SERC, so you can see it puts up a black badge.

**Pull request merged**
