### PR TITLE
Merge data and metadata from PREMIS-stormsurge

### PR DESCRIPTION
**Pull request by stephpenn1**
FYI @ahopple I moved your `teros.R` script and the R project to a new folder called `R_scripts`

@bpbond where does the 7810 licor data live? I didn't see it in PREMIS-stormsurge or in here?

This pull request also creates a `Design` folder for metadata (including the inventory script, FYI @aestearns01)

### CODE REVIEW

**Comment by bpbond** [comment]
@stephpenn1 If you moved the Rstudio project file, that will probably break the scripts. Did you check?

The 7810 data are in the TEMPESTX repository.

**Comment by stephpenn1** [comment]
@bpbond No I did not check. Should I update the code paths?

**Comment by bpbond** [comment]
I think if you break it, yes, you fix it 😜

**Comment by bpbond** [comment]
We could start using the [here package](https://here.r-lib.org) to be more robust to this kind of thing.

**Comment by stephpenn1** [comment]
Ok @bpbond I've repented my sins

**Review by bpbond — APPROVED** [review]

**Pull request merged**
