### PR TITLE
Use compasstools functions to read data

### PR DESCRIPTION
**Pull request by bpbond**
This draft PR moves the sapflow-, TEROS-, and Aqua TROLL-reading code out of this repository and into a new [compasstools](https://github.com/COMPASS-DOE/compasstools) package. This has several advantages I think:
* Less code here 🎉 
* Dedicated [test code](https://github.com/COMPASS-DOE/compasstools/tree/main/tests/testthat) for the file-reading functions 
* The data workflows, and your planned synoptic dashboard, don't have to duplicate this code—they can just use `compasstools`

Dashboard still runs fine on my system.

Before I go any farther, does this make sense to you? Any concerns?

### CODE REVIEW

**Comment by bpbond** [comment]
@stephpenn1 Ready for review

**Comment by stephpenn1** [comment]
Apologies that I am just now getting to this - looks AWESOME and runs on my local as well. Merging!

**Review by stephpenn1 — APPROVED** [review]

**Comment by stephpenn1** [comment]
Can this branch be deleted?

**Comment by bpbond** [comment]
Sure. This branch doesn't include using the `min_timestamp` functionality of compasstools, but that's probably not crucial for now.

Very glad it ran locally without any problem!

**Pull request merged**
